### ISSUE TITLE
Add uses for africaplants, golden carrot, and other medicinal stuffs

### ISSUE THREAD

**Issue by KaylebJay** [KaylebJay/tunnelers-bugz#21]
To be done in a future mod. 
Any ideas or enlightenment would be nice, but just a fair warning: this is a bit far off and is more of a reminder note for me.

**Comment by fluxionary** [comment]
Conferring limited-duration status effects would be really useful. Some ideas:
* Lava/fire resistance or immunity
* Increased breathing time underwater
* Speed boost
* Jump boost
* Increased health regeneration
* Animal Magnetism (turns hostile mobs friendly)
* Night Vision (this doesn't work in caves because Reasons)
* Eagle eyes (allows "zoom" like binoculars)
* Spatial Memory (allows using the minimap)
* Echolocation (allows using the radar minimap)

**Comment by KaylebJay** [comment]
Replaced by https://github.com/KaylebJay/tunnelers-bugz/issues/75
